language: c
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
      env:
        - PROTOBUF_VERSION=3.4.0
    - os: osx
      env:
        - PROTOBUF_VERSION=3.6.1
        # Include paths for brew packages e.g. SDL2
        - CFLAGS="-I/usr/local/include -L/usr/local/lib"
before_script:
  # install linters
  - make install-linters
  # Define env vars for Linux builds
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then export CHECK_PATH="$(pwd)/check-0.12.0"; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${CHECK_PATH}/src" ; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then export PATH="$PATH:$(pwd)/protoc/bin" ; echo "PATH=$PATH"; fi
  # Install OS-specific test and build dependencies
  - eval "./ci-scripts/install-${TRAVIS_OS_NAME}.sh"
  # Upgrade protobuf python
  - pip3 install --user --upgrade protobuf
  - pip3 install --user "protobuf==${PROTOBUF_VERSION}" ecdsa
  - pip install --user --upgrade protobuf
script:
  - make lint
  - make -C skycoin-api test
  - make -C skycoin-api clean
  - make emulator
  - make clean
  - make full-firmware
  - md5sum tiny-firmware/bootloader/combine/*.bin
  - md5sum full-firmware-no-mem-protect.bin
