language: c
matrix:
  include:
    - os: linux
      env:
        - PIP='sudo pip'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
    - os: osx

before_script:
  - sh "./tiny-firmware/protob/ci-scripts/install-${TRAVIS_OS_NAME}.sh" ;
  # Define env vars for Linux builds
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
    ls -l /usr/local/bin/protoc ;
    export CHECK_PATH="$(pwd)/check-0.12.0" ;
    export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${CHECK_PATH}/src" ;
    export PATH="/usr/local/bin:$(pwd)/protoc/bin:$PATH" ;
    echo "PATH=$PATH";
    echo "PIP=$PIP";
    fi
  # Define env vars for osx builds
  # Include paths for brew packages e.g. SDL2
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    export CHECK_PATH="$(brew --prefix check)" ;
    export DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}:${CHECK_PATH}/lib" ;
    export SDL_INCLUDE="$(brew --prefix sdl2)/include/SDL2" ;
    fi
  # Install OS-specific test and build dependencies
  - eval "./ci-scripts/install-${TRAVIS_OS_NAME}.sh"
  # Install linters
  - make install-linters
script:
  - find tiny-firmware/protob/nanopb/vendor/nanopb
  - make lint
  - make -C tiny-firmware/protob install-deps-nanopb
  - make -C tiny-firmware/protob install-protoc
  - make -C tiny-firmware/protob/nanopb/vendor/nanopb/generator/proto
  - find tiny-firmware/protob/nanopb/vendor/nanopb
  - make clean
  - make test
  - make clean
  - make emulator
  - make clean
  - make full-firmware
  - md5sum tiny-firmware/bootloader/combine/*.bin
  - md5sum full-firmware-no-mem-protect.bin
notifications:
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
